config/routes.rb
Shop::Application.routes.draw do
  get 'admin' => 'admin#index'
  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  resources :users

  resources :orders

  resources :line_items

  resources :carts

  get "store/index"
  resources :products do
    get :who_bought, on: :member
  end

  root :to => 'store#index', :as => 'store'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shop</title>
  <%= stylesheet_link_tag "depot", :media => "all" %>
  <%= javascript_include_tag :application %>
  <link href='http://fonts.googleapis.com/css?family=Metrophobic' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
	<body id="store" >
		<div id="banner" >
			<%= image_tag("logo.png") %>
				<%= @page_title || "Pragmatic Bookshelf" %>
		</div>
		<div id="columns">
			<div id="side">
				<div id="cart" >
					<% if @cart %>
						<%= hidden_div_if(@cart.line_items.empty?, :id => "cart") do %>
						<%= render @cart %>
						<% end %>
					<% end %>
				</div>

				<a href="http://www....">Home</a><br />
				<a href="http://www..../faq">Questions</a><br />
				<a href="http://www..../news">News</a><br />
				<a href="http://www..../contact">Contact</a><br />

				<% if session[:user_id] %>
					<br>
					<%= link_to "Orders", orders_path %>
					<%= link_to "Products", products_path %>
					<%= link_to "Useers", users_path %>
					<br>
					<%= button_to "Logout", logout_path, method: :delete %>
				<% end %>

			</div>
			<div id="main">
				<%= yield %>
			</div>
		</div>
</body>
</html>